[project]
name = "cards-mvp"
version = "0.1.0"
description = "Little mvp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "orjson>=3.11.5",
    "pyyaml>=6.0.3",
    "redis>=7.1.0",
    "uvicorn>=0.40.0",
]
